import { SinglePlayerStageInfo, GameMode, Player, SinglePlayerLevel, SinglePlayerMissionInfo, SinglePlayerMissionLevelInfo } from '../types/index.js';

// 레벨별 수련과제 데이터 생성 헬퍼
const createMissionLevels = (
    baseProductionRate: number[], // 레벨별 생산속도 (분)
    baseRewardAmount: number[], // 레벨별 생산량
    baseMaxCapacity: number[], // 레벨별 최대생산량
    unlockStageIdLevel10?: string // 레벨 10 오픈조건
): SinglePlayerMissionLevelInfo[] => {
    return Array.from({ length: 10 }, (_, i) => ({
        level: i + 1,
        unlockStageId: i === 9 ? unlockStageIdLevel10 : undefined,
        productionRateMinutes: baseProductionRate[i],
        rewardAmount: baseRewardAmount[i],
        maxCapacity: baseMaxCapacity[i],
    }));
};

export const SINGLE_PLAYER_MISSIONS: SinglePlayerMissionInfo[] = [
    {
        id: 'mission_attendance',
        name: '출석하기',
        description: '바둑학원에 등원하기',
        unlockStageId: '입문-1',
        rewardType: 'gold',
        image: '/images/single/Mission1.png',
        levels: createMissionLevels(
            [5, 5, 5, 5, 5, 5, 4.5, 4, 3.5, 3], // 생산속도 (분)
            [5, 5, 5, 5, 5, 10, 10, 10, 10, 10], // 생산량
            [50, 60, 70, 80, 90, 100, 110, 120, 130, 150], // 최대생산량
            '입문-1' // 레벨 10 오픈조건
        )
    },
    {
        id: 'mission_complete_game',
        name: '바둑한판 완성',
        description: '계가까지 바둑두기',
        unlockStageId: '입문-20',
        rewardType: 'gold',
        image: '/images/single/Mission2.png',
        levels: createMissionLevels(
            [5, 5, 5, 5, 5, 5, 4.5, 4, 3.5, 3],
            [10, 10, 10, 10, 10, 20, 20, 20, 20, 20],
            [150, 160, 170, 180, 200, 220, 240, 260, 280, 300],
            '입문-20'
        )
    },
    {
        id: 'mission_rival_match',
        name: '맞수와 대국',
        description: '최선을 다해 승부하기',
        unlockStageId: '초급-20',
        rewardType: 'gold',
        image: '/images/single/Mission3.png',
        levels: createMissionLevels(
            [5, 5, 5, 5, 5, 5, 4.5, 4, 3.5, 3],
            [20, 20, 20, 20, 20, 20, 30, 30, 30, 30],
            [300, 340, 380, 420, 460, 500, 540, 600, 660, 750],
            '초급-20'
        )
    },
    {
        id: 'mission_study_joseki',
        name: '정석/포석 공부',
        description: '정석/포석 익히기',
        unlockStageId: '중급-20',
        rewardType: 'diamonds',
        image: '/images/single/Mission4.png',
        levels: createMissionLevels(
            [60, 58, 56, 54, 52, 50, 47, 44, 41, 35],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [2, 2, 2, 2, 3, 3, 3, 3, 3, 4],
            '중급-20'
        )
    },
    {
        id: 'mission_league',
        name: '리그전참가',
        description: '집중하여 연속 바둑두기',
        unlockStageId: '고급-20',
        rewardType: 'gold',
        image: '/images/single/Mission5.png',
        levels: createMissionLevels(
            [5, 5, 5, 5, 5, 5, 4.5, 4, 3.5, 3],
            [50, 50, 50, 50, 50, 50, 50, 50, 100, 100],
            [500, 550, 600, 650, 700, 750, 800, 850, 900, 1000],
            '고급-20'
        )
    },
    {
        id: 'mission_ai_match',
        name: '인공지능대국',
        description: '배울점을 끊임없이 찾기',
        unlockStageId: '유단자-20',
        rewardType: 'diamonds',
        image: '/images/single/Mission6.png',
        levels: createMissionLevels(
            [60, 58, 56, 54, 52, 50, 47, 44, 41, 35],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [3, 3, 3, 3, 4, 4, 4, 4, 4, 5],
            '유단자-20'
        )
    },
];


export const SINGLE_PLAYER_STAGES: SinglePlayerStageInfo[] = [
    // Data from the spreadsheet image
    // 입문 1~10: 따내기 바둑 (흑에게 15턴 제한)
    { id: '입문-1', name: '스테이지 1', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 5, white: 5 }, placements: { black: 2, white: 2, blackPattern: 0, whitePattern: 1, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, blackTurnLimit: 15, rewards: { firstClear: { gold: 100, exp: 10 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-2', name: '스테이지 2', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 5, white: 5 }, placements: { black: 2, white: 2, blackPattern: 0, whitePattern: 1, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, blackTurnLimit: 15, rewards: { firstClear: { gold: 100, exp: 11 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-3', name: '스테이지 3', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 5, white: 5 }, placements: { black: 2, white: 2, blackPattern: 1, whitePattern: 1, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, blackTurnLimit: 15, rewards: { firstClear: { gold: 100, exp: 12 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-4', name: '스테이지 4', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 5, white: 5 }, placements: { black: 2, white: 2, blackPattern: 2, whitePattern: 1, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, blackTurnLimit: 15, rewards: { firstClear: { gold: 100, exp: 13 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-5', name: '스테이지 5', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 6, white: 6 }, placements: { black: 2, white: 3, blackPattern: 2, whitePattern: 1, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, blackTurnLimit: 15, rewards: { firstClear: { gold: 100, exp: 14, items: [{itemId: "골드 꾸러미1", quantity: 1}] }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-6', name: '스테이지 6', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 6, white: 6 }, placements: { black: 3, white: 5, blackPattern: 2, whitePattern: 0, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, blackTurnLimit: 15, rewards: { firstClear: { gold: 100, exp: 15 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-7', name: '스테이지 7', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 6, white: 6 }, placements: { black: 3, white: 4, blackPattern: 2, whitePattern: 2, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, blackTurnLimit: 15, rewards: { firstClear: { gold: 100, exp: 16 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-8', name: '스테이지 8', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 6, white: 6 }, placements: { black: 3, white: 5, blackPattern: 3, whitePattern: 2, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, blackTurnLimit: 15, rewards: { firstClear: { gold: 100, exp: 17 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-9', name: '스테이지 9', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 6, white: 6 }, placements: { black: 3, white: 4, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 3, byoyomiTime: 0, byoyomiCount: 3 }, blackTurnLimit: 15, rewards: { firstClear: { gold: 100, exp: 18 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-10', name: '스테이지 10', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 7, white: 5 }, placements: { black: 4, white: 7, blackPattern: 2, whitePattern: 3 }, timeControl: { type: 'fischer', mainTime: 5, increment: 10 }, blackTurnLimit: 15, rewards: { firstClear: { gold: 150, exp: 20, items: [{itemId: "장비 상자 I", quantity: 1}] }, repeatClear: { gold: 10, exp: 15 } } },
    // 입문 11~20: 살리기 바둑 모드 (AI가 정해진 턴 동안 도망가며 살아남기)
    { id: '입문-11', name: '스테이지 11', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 9, targetScore: { black: 5, white: 0 }, placements: { black: 3, white: 13, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, survivalTurns: 15, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-12', name: '스테이지 12', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 9, targetScore: { black: 5, white: 0 }, placements: { black: 4, white: 14, blackPattern: 1, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, survivalTurns: 15, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-13', name: '스테이지 13', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 9, targetScore: { black: 5, white: 0 }, placements: { black: 5, white: 15, blackPattern: 2, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, survivalTurns: 15, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-14', name: '스테이지 14', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 9, targetScore: { black: 5, white: 0 }, placements: { black: 4, white: 15, blackPattern: 2, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, survivalTurns: 15, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-15', name: '스테이지 15', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 9, targetScore: { black: 5, white: 0 }, placements: { black: 3, white: 14, blackPattern: 2, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, survivalTurns: 15, rewards: { firstClear: { gold: 150, exp: 20, items: [{itemId: "재료 상자 I", quantity: 1}] }, repeatClear: { gold: 10, exp: 10 } } },
    { id: '입문-16', name: '스테이지 16', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 9, targetScore: { black: 5, white: 0 }, placements: { black: 2, white: 13, blackPattern: 2, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, survivalTurns: 16, rewards: { firstClear: { gold: 150, exp: 30 }, repeatClear: { gold: 10, exp: 15 } } },
    { id: '입문-17', name: '스테이지 17', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 9, targetScore: { black: 5, white: 0 }, placements: { black: 3, white: 15, blackPattern: 3, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, survivalTurns: 17, rewards: { firstClear: { gold: 150, exp: 30 }, repeatClear: { gold: 10, exp: 15 } } },
    { id: '입문-18', name: '스테이지 18', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 9, targetScore: { black: 5, white: 0 }, placements: { black: 4, white: 16, blackPattern: 4, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, survivalTurns: 18, rewards: { firstClear: { gold: 150, exp: 30 }, repeatClear: { gold: 10, exp: 15 } } },
    { id: '입문-19', name: '스테이지 19', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 9, targetScore: { black: 5, white: 0 }, placements: { black: 5, white: 17, blackPattern: 5, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, survivalTurns: 19, rewards: { firstClear: { gold: 150, exp: 30 }, repeatClear: { gold: 10, exp: 15 } } },
    { id: '입문-20', name: '스테이지 20', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 9, targetScore: { black: 5, white: 0 }, placements: { black: 5, white: 18, blackPattern: 6, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 }, survivalTurns: 20, rewards: { firstClear: { gold: 200, exp: 30, items: [{itemId: "다이아 꾸러미1", quantity: 1}] }, repeatClear: { gold: 10, exp: 15 } } },
    // 초급
    { id: '초급-1', name: '스테이지 1', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 9, white: 8 }, placements: { black: 4, white: 6, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 200, exp: 30 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-2', name: '스테이지 2', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 9, white: 8 }, placements: { black: 5, white: 8, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 200, exp: 32 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-3', name: '스테이지 3', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 9, white: 8 }, placements: { black: 3, white: 7, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 200, exp: 34 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-4', name: '스테이지 4', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 9, white: 8 }, placements: { black: 6, white: 9, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 200, exp: 36 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-5', name: '스테이지 5', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 10, white: 9 }, placements: { black: 8, white: 13, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 200, exp: 38, items: [{itemId: "골드 꾸러미2", quantity: 1}] }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-6', name: '스테이지 6', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 10, white: 9 }, placements: { black: 4, white: 9, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 200, exp: 40 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-7', name: '스테이지 7', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 10, white: 9 }, placements: { black: 7, white: 10, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 200, exp: 42 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-8', name: '스테이지 8', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 10, white: 9 }, placements: { black: 5, white: 11, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 200, exp: 44, items: [{itemId: "재료 상자 I", quantity: 1}] }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-9', name: '스테이지 9', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 10, white: 9 }, placements: { black: 6, white: 12, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 200, exp: 46 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-10', name: '스테이지 10', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 11, white: 9 }, placements: { black: 3, white: 8, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 250, exp: 50, items: [{itemId: "장비 상자 II", quantity: 1}] }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-11', name: '스테이지 11', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 11, white: 9 }, placements: { black: 4, white: 9, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 250, exp: 52 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-12', name: '스테이지 12', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 11, white: 9 }, placements: { black: 5, white: 10, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 250, exp: 54 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-13', name: '스테이지 13', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 11, white: 9 }, placements: { black: 6, white: 11, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 250, exp: 56 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-14', name: '스테이지 14', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 11, white: 9 }, placements: { black: 7, white: 12, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 250, exp: 58 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-15', name: '스테이지 15', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 12, white: 10 }, placements: { black: 5, white: 13, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 250, exp: 60, items: [{itemId: "재료 상자 II", quantity: 1}] }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-16', name: '스테이지 16', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 12, white: 10 }, placements: { black: 6, white: 14, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 250, exp: 62 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-17', name: '스테이지 17', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 12, white: 10 }, placements: { black: 7, white: 15, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 250, exp: 64 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-18', name: '스테이지 18', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 12, white: 10 }, placements: { black: 8, white: 16, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 250, exp: 66 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-19', name: '스테이지 19', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 12, white: 10 }, placements: { black: 9, white: 17, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 250, exp: 100 }, repeatClear: { gold: 30, exp: 20 } }, autoScoringTurns: 40 },
    { id: '초급-20', name: '스테이지 20', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 15, white: 12 }, placements: { black: 5, white: 20, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 300, exp: 120, items: [{itemId: "다이아 꾸러미2", quantity: 1}], bonus: '스탯10' }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 40 },
    // 중급
    { id: '중급-1', name: '스테이지 1', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 7, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 3 },
    { id: '중급-2', name: '스테이지 2', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 5, white: 8, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 3 },
    { id: '중급-3', name: '스테이지 3', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 3, white: 9, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 3 },
    { id: '중급-4', name: '스테이지 4', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 6, white: 10, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 3 },
    { id: '중급-5', name: '스테이지 5', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 8, white: 13, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 150, items: [{itemId: "골드 꾸러미3", quantity: 1}] }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 3 },
    { id: '중급-6', name: '스테이지 6', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 11, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 3 },
    { id: '중급-7', name: '스테이지 7', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 7, white: 12, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 3 },
    { id: '중급-8', name: '스테이지 8', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 5, white: 13, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 3 },
    { id: '중급-9', name: '스테이지 9', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 6, white: 14, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 3 },
    { id: '중급-10', name: '스테이지 10', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 3, white: 8, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 200, items: [{itemId: "장비 상자 III", quantity: 1}] }, repeatClear: { gold: 50, exp: 50 } }, autoScoringTurns: 60, missileCount: 3 },
    { id: '중급-11', name: '스테이지 11', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 9, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 2 },
    { id: '중급-12', name: '스테이지 12', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 5, white: 10, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 2 },
    { id: '중급-13', name: '스테이지 13', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 6, white: 11, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 2 },
    { id: '중급-14', name: '스테이지 14', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 7, white: 12, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 2 },
    { id: '중급-15', name: '스테이지 15', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 3, white: 6, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 200, items: [{itemId: "재료 상자 III", quantity: 1}] }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 2 },
    { id: '중급-16', name: '스테이지 16', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 8, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 2 },
    { id: '중급-17', name: '스테이지 17', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 6, white: 6, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 2 },
    { id: '중급-18', name: '스테이지 18', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 8, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 2 },
    { id: '중급-19', name: '스테이지 19', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 6, white: 6, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, autoScoringTurns: 60, missileCount: 2 },
    { id: '중급-20', name: '스테이지 20', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 0, white: 0 }, placements: { black: 5, white: 13, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 250, items: [{itemId: "다이아 꾸러미3", quantity: 1}] }, repeatClear: { gold: 50, exp: 50 } }, autoScoringTurns: 60, missileCount: 1 },
    // 고급
    { id: '고급-1', name: '스테이지 1', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 8, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-2', name: '스테이지 2', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 5, white: 10, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-3', name: '스테이지 3', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 6, white: 11, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-4', name: '스테이지 4', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 7, white: 12, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-5', name: '스테이지 5', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 8, white: 14, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 250, items: [{itemId: "골드 꾸러미4", quantity: 1}] }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-6', name: '스테이지 6', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 9, white: 14, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-7', name: '스테이지 7', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 8, white: 13, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-8', name: '스테이지 8', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 7, white: 12, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-9', name: '스테이지 9', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 5, white: 10, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-10', name: '스테이지 10', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 3, white: 9, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 300, items: [{itemId: "장비 상자 IV", quantity: 1}] }, repeatClear: { gold: 100, exp: 70 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-11', name: '스테이지 11', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 10, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-12', name: '스테이지 12', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 5, white: 11, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-13', name: '스테이지 13', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 10, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-14', name: '스테이지 14', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 10, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-15', name: '스테이지 15', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 12, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 250, items: [{itemId: "재료 상자 IV", quantity: 1}] }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-16', name: '스테이지 16', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 11, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-17', name: '스테이지 17', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 11, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-18', name: '스테이지 18', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 11, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-19', name: '스테이지 19', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 5, white: 12, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    { id: '고급-20', name: '스테이지 20', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 5, white: 14, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 350, items: [{itemId: "다이아 꾸러미4", quantity: 1}] }, repeatClear: { gold: 100, exp: 80 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 3 },
    // 유단자
    { id: '유단자-1', name: '스테이지 1', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 25, white: 10 }, placements: { black: 4, white: 14, blackPattern: 5, whitePattern: 4, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 150, exp: 50 } }, blackTurnLimit: 35 },
    { id: '유단자-2', name: '스테이지 2', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 25, white: 9 }, placements: { black: 3, white: 14, blackPattern: 5, whitePattern: 3, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 150, exp: 50 } }, blackTurnLimit: 35 },
    { id: '유단자-3', name: '스테이지 3', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 25, white: 8 }, placements: { black: 4, white: 16, blackPattern: 7, whitePattern: 2, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 150, exp: 50 } }, blackTurnLimit: 35 },
    { id: '유단자-4', name: '스테이지 4', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 25, white: 7 }, placements: { black: 4, white: 17, blackPattern: 7, whitePattern: 2, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 150, exp: 50 } }, blackTurnLimit: 35 },
    { id: '유단자-5', name: '스테이지 5', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 30, white: 6 }, placements: { black: 4, white: 18, blackPattern: 8, whitePattern: 2, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 400, items: [{itemId: "재료 상자 V", quantity: 1}] }, repeatClear: { gold: 150, exp: 50 } }, blackTurnLimit: 35 },
    { id: '유단자-6', name: '스테이지 6', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 15, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 200, exp: 50 } }, autoScoringTurns: 80 },
    { id: '유단자-7', name: '스테이지 7', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 3, white: 14, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 200, exp: 50 } }, autoScoringTurns: 80 },
    { id: '유단자-8', name: '스테이지 8', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 3, white: 15, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 200, exp: 50 } }, autoScoringTurns: 80 },
    { id: '유단자-9', name: '스테이지 9', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 16, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 200, exp: 50 } }, autoScoringTurns: 80 },
    { id: '유단자-10', name: '스테이지 10', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 16, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'fischer', mainTime: 3, increment: 5 }, rewards: { firstClear: { gold: 700, exp: 500, items: [{itemId: "장비 상자 V", quantity: 1}] }, repeatClear: { gold: 200, exp: 90 } }, autoScoringTurns: 80 },
    { id: '유단자-11', name: '스테이지 11', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 16, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 300 }, repeatClear: { gold: 300, exp: 50 } }, autoScoringTurns: 80, missileCount: 3 },
    { id: '유단자-12', name: '스테이지 12', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 3, white: 15, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 300 }, repeatClear: { gold: 300, exp: 50 } }, autoScoringTurns: 80, missileCount: 3 },
    { id: '유단자-13', name: '스테이지 13', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 3, white: 16, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 300 }, repeatClear: { gold: 300, exp: 50 } }, autoScoringTurns: 80, missileCount: 3 },
    { id: '유단자-14', name: '스테이지 14', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 17, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 300 }, repeatClear: { gold: 300, exp: 50 } }, autoScoringTurns: 80, missileCount: 3 },
    { id: '유단자-15', name: '스테이지 15', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 17, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 400, items: [{itemId: "재료 상자 VI", quantity: 1}] }, repeatClear: { gold: 300, exp: 50 } }, autoScoringTurns: 80, missileCount: 3 },
    { id: '유단자-16', name: '스테이지 16', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 17, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 350 }, repeatClear: { gold: 300, exp: 50 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 2 },
    { id: '유단자-17', name: '스테이지 17', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 3, white: 16, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 350 }, repeatClear: { gold: 300, exp: 50 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 2 },
    { id: '유단자-18', name: '스테이지 18', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 3, white: 17, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 350 }, repeatClear: { gold: 300, exp: 50 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 2 },
    { id: '유단자-19', name: '스테이지 19', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 18, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 350 }, repeatClear: { gold: 300, exp: 50 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 2 },
    { id: '유단자-20', name: '스테이지 20', level: SinglePlayerLevel.유단자, actionPointCost: 5, boardSize: 13, targetScore: { black: 0, white: 0 }, placements: { black: 4, white: 25, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 }, timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 1000, items: [{itemId: "장비 상자 VI", quantity: 1}] }, repeatClear: { gold: 300, exp: 100 } }, autoScoringTurns: 80, hiddenCount: 1, scanCount: 2 },
];
  
