import { SinglePlayerStageInfo } from '../types/index.js';

// 도전의 탑 스테이지 정보 (1-20층: 따내기 바둑)
export const TOWER_STAGES: SinglePlayerStageInfo[] = [
    // 1층
    {
        id: 'tower-1',
        name: '1층',
        level: 'tower' as any, // 도전의 탑은 별도 레벨로 관리
        actionPointCost: 2,
        boardSize: 7,
        targetScore: { black: 5, white: 5 },
        placements: { black: 5, white: 4, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 15,
        rewards: { firstClear: { gold: 100, exp: 30 }, repeatClear: { gold: 10, exp: 30 } }
    },
    // 2층
    {
        id: 'tower-2',
        name: '2층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 7,
        targetScore: { black: 6, white: 5 },
        placements: { black: 4, white: 4, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 15,
        rewards: { firstClear: { gold: 100, exp: 30 }, repeatClear: { gold: 10, exp: 30 } }
    },
    // 3층
    {
        id: 'tower-3',
        name: '3층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 7,
        targetScore: { black: 7, white: 5 },
        placements: { black: 3, white: 4, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 15,
        rewards: { firstClear: { gold: 100, exp: 30 }, repeatClear: { gold: 10, exp: 30 } }
    },
    // 4층
    {
        id: 'tower-4',
        name: '4층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 7,
        targetScore: { black: 8, white: 5 },
        placements: { black: 2, white: 4, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 15,
        rewards: { firstClear: { gold: 100, exp: 30 }, repeatClear: { gold: 10, exp: 30 } }
    },
    // 5층
    {
        id: 'tower-5',
        name: '5층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 7,
        targetScore: { black: 9, white: 5 },
        placements: { black: 1, white: 4, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 15,
        rewards: { firstClear: { gold: 0, exp: 30, items: [{ itemId: '골드 꾸러미1', quantity: 1 }] }, repeatClear: { gold: 10, exp: 30 } }
    },
    // 6층
    {
        id: 'tower-6',
        name: '6층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 7,
        targetScore: { black: 10, white: 5 },
        placements: { black: 4, white: 5, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 16,
        rewards: { firstClear: { gold: 100, exp: 30 }, repeatClear: { gold: 10, exp: 30 } }
    },
    // 7층
    {
        id: 'tower-7',
        name: '7층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 7,
        targetScore: { black: 11, white: 5 },
        placements: { black: 4, white: 6, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 17,
        rewards: { firstClear: { gold: 100, exp: 30 }, repeatClear: { gold: 10, exp: 30 } }
    },
    // 8층
    {
        id: 'tower-8',
        name: '8층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 7,
        targetScore: { black: 12, white: 5 },
        placements: { black: 4, white: 7, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 18,
        rewards: { firstClear: { gold: 100, exp: 30 }, repeatClear: { gold: 10, exp: 30 } }
    },
    // 9층
    {
        id: 'tower-9',
        name: '9층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 7,
        targetScore: { black: 13, white: 5 },
        placements: { black: 4, white: 8, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 19,
        rewards: { firstClear: { gold: 100, exp: 30 }, repeatClear: { gold: 10, exp: 30 } }
    },
    // 10층
    {
        id: 'tower-10',
        name: '10층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 7,
        targetScore: { black: 14, white: 5 },
        placements: { black: 4, white: 10, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 20,
        rewards: { firstClear: { gold: 0, exp: 30, items: [{ itemId: '장비상자1', quantity: 1 }] }, repeatClear: { gold: 10, exp: 30 } }
    },
    // 11층
    {
        id: 'tower-11',
        name: '11층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 9,
        targetScore: { black: 15, white: 5 },
        placements: { black: 5, white: 11, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 25,
        rewards: { firstClear: { gold: 150, exp: 50 }, repeatClear: { gold: 15, exp: 50 } }
    },
    // 12층
    {
        id: 'tower-12',
        name: '12층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 9,
        targetScore: { black: 16, white: 5 },
        placements: { black: 5, white: 12, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 25,
        rewards: { firstClear: { gold: 150, exp: 50 }, repeatClear: { gold: 15, exp: 50 } }
    },
    // 13층
    {
        id: 'tower-13',
        name: '13층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 9,
        targetScore: { black: 17, white: 5 },
        placements: { black: 5, white: 13, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 25,
        rewards: { firstClear: { gold: 150, exp: 50 }, repeatClear: { gold: 15, exp: 50 } }
    },
    // 14층
    {
        id: 'tower-14',
        name: '14층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 9,
        targetScore: { black: 18, white: 5 },
        placements: { black: 5, white: 14, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 25,
        rewards: { firstClear: { gold: 150, exp: 50 }, repeatClear: { gold: 15, exp: 50 } }
    },
    // 15층
    {
        id: 'tower-15',
        name: '15층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 9,
        targetScore: { black: 19, white: 5 },
        placements: { black: 5, white: 15, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 25,
        rewards: { firstClear: { gold: 0, exp: 50, items: [{ itemId: '재료상자1', quantity: 1 }] }, repeatClear: { gold: 15, exp: 50 } }
    },
    // 16층
    {
        id: 'tower-16',
        name: '16층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 9,
        targetScore: { black: 20, white: 5 },
        placements: { black: 5, white: 16, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 26,
        rewards: { firstClear: { gold: 150, exp: 50 }, repeatClear: { gold: 15, exp: 50 } }
    },
    // 17층
    {
        id: 'tower-17',
        name: '17층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 9,
        targetScore: { black: 21, white: 5 },
        placements: { black: 5, white: 17, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 27,
        rewards: { firstClear: { gold: 150, exp: 50 }, repeatClear: { gold: 15, exp: 50 } }
    },
    // 18층
    {
        id: 'tower-18',
        name: '18층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 9,
        targetScore: { black: 22, white: 5 },
        placements: { black: 5, white: 18, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 28,
        rewards: { firstClear: { gold: 150, exp: 50 }, repeatClear: { gold: 15, exp: 50 } }
    },
    // 19층
    {
        id: 'tower-19',
        name: '19층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 9,
        targetScore: { black: 23, white: 5 },
        placements: { black: 5, white: 19, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 29,
        rewards: { firstClear: { gold: 150, exp: 50 }, repeatClear: { gold: 15, exp: 50 } }
    },
    // 20층
    {
        id: 'tower-20',
        name: '20층',
        level: 'tower' as any,
        actionPointCost: 2,
        boardSize: 9,
        targetScore: { black: 25, white: 5 },
        placements: { black: 5, white: 20, blackPattern: 0, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        blackTurnLimit: 30,
        rewards: { firstClear: { gold: 0, exp: 50, items: [{ itemId: '다이아꾸러미1', quantity: 1 }] }, repeatClear: { gold: 15, exp: 50 } }
    },
    // 21-30층: 자동계가 턴 40턴, 미사일+히든 합쳐진 형태
    {
        id: 'tower-21',
        name: '21층',
        level: 'tower' as any,
        actionPointCost: 3,
        boardSize: 9,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 15, blackPattern: 2, whitePattern: 1, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 40,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 200, exp: 50 }, repeatClear: { gold: 20, exp: 50 } }
    },
    {
        id: 'tower-22',
        name: '22층',
        level: 'tower' as any,
        actionPointCost: 3,
        boardSize: 9,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 15, blackPattern: 2, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 40,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 200, exp: 50 }, repeatClear: { gold: 20, exp: 50 } }
    },
    {
        id: 'tower-23',
        name: '23층',
        level: 'tower' as any,
        actionPointCost: 3,
        boardSize: 9,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 14, blackPattern: 3, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 40,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 200, exp: 50 }, repeatClear: { gold: 20, exp: 50 } }
    },
    {
        id: 'tower-24',
        name: '24층',
        level: 'tower' as any,
        actionPointCost: 3,
        boardSize: 9,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 15, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 40,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 200, exp: 50 }, repeatClear: { gold: 20, exp: 50 } }
    },
    {
        id: 'tower-25',
        name: '25층',
        level: 'tower' as any,
        actionPointCost: 3,
        boardSize: 9,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 14, blackPattern: 4, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 40,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 50, items: [{ itemId: '골드 꾸러미2', quantity: 1 }] }, repeatClear: { gold: 20, exp: 50 } }
    },
    {
        id: 'tower-26',
        name: '26층',
        level: 'tower' as any,
        actionPointCost: 3,
        boardSize: 9,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 15, blackPattern: 4, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 40,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 200, exp: 50 }, repeatClear: { gold: 20, exp: 50 } }
    },
    {
        id: 'tower-27',
        name: '27층',
        level: 'tower' as any,
        actionPointCost: 3,
        boardSize: 9,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 15, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 40,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 200, exp: 50 }, repeatClear: { gold: 20, exp: 50 } }
    },
    {
        id: 'tower-28',
        name: '28층',
        level: 'tower' as any,
        actionPointCost: 3,
        boardSize: 9,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 13, blackPattern: 2, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 40,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 200, exp: 50 }, repeatClear: { gold: 20, exp: 50 } }
    },
    {
        id: 'tower-29',
        name: '29층',
        level: 'tower' as any,
        actionPointCost: 3,
        boardSize: 9,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 15, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 40,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 200, exp: 50 }, repeatClear: { gold: 20, exp: 50 } }
    },
    {
        id: 'tower-30',
        name: '30층',
        level: 'tower' as any,
        actionPointCost: 3,
        boardSize: 9,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 15, blackPattern: 2, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 40,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 50, items: [{ itemId: '장비상자2', quantity: 1 }] }, repeatClear: { gold: 20, exp: 50 } }
    },
    // 31-50층: 자동계가 턴 50턴
    {
        id: 'tower-31',
        name: '31층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 16, blackPattern: 2, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 250, exp: 80 }, repeatClear: { gold: 25, exp: 80 } }
    },
    {
        id: 'tower-32',
        name: '32층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 14, blackPattern: 1, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 250, exp: 80 }, repeatClear: { gold: 25, exp: 80 } }
    },
    {
        id: 'tower-33',
        name: '33층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 15, blackPattern: 2, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 250, exp: 80 }, repeatClear: { gold: 25, exp: 80 } }
    },
    {
        id: 'tower-34',
        name: '34층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 15, blackPattern: 3, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 250, exp: 80 }, repeatClear: { gold: 25, exp: 80 } }
    },
    {
        id: 'tower-35',
        name: '35층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 16, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 80, items: [{ itemId: '재료상자2', quantity: 1 }] }, repeatClear: { gold: 25, exp: 80 } }
    },
    {
        id: 'tower-36',
        name: '36층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 15, blackPattern: 2, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 250, exp: 80 }, repeatClear: { gold: 25, exp: 80 } }
    },
    {
        id: 'tower-37',
        name: '37층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 14, blackPattern: 4, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 250, exp: 80 }, repeatClear: { gold: 25, exp: 80 } }
    },
    {
        id: 'tower-38',
        name: '38층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 16, blackPattern: 3, whitePattern: 1, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 250, exp: 80 }, repeatClear: { gold: 25, exp: 80 } }
    },
    {
        id: 'tower-39',
        name: '39층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 15, blackPattern: 1, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 250, exp: 80 }, repeatClear: { gold: 25, exp: 80 } }
    },
    {
        id: 'tower-40',
        name: '40층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 16, blackPattern: 5, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 80, items: [{ itemId: '다이아꾸러미2', quantity: 1 }] }, repeatClear: { gold: 25, exp: 80 } }
    },
    {
        id: 'tower-41',
        name: '41층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 16, blackPattern: 5, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 300, exp: 80 }, repeatClear: { gold: 30, exp: 80 } }
    },
    {
        id: 'tower-42',
        name: '42층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 16, blackPattern: 5, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 300, exp: 80 }, repeatClear: { gold: 30, exp: 80 } }
    },
    {
        id: 'tower-43',
        name: '43층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 15, blackPattern: 4, whitePattern: 5, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 300, exp: 80 }, repeatClear: { gold: 30, exp: 80 } }
    },
    {
        id: 'tower-44',
        name: '44층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 15, blackPattern: 3, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 300, exp: 80 }, repeatClear: { gold: 30, exp: 80 } }
    },
    {
        id: 'tower-45',
        name: '45층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 16, blackPattern: 3, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 80, items: [{ itemId: '골드 꾸러미3', quantity: 1 }] }, repeatClear: { gold: 30, exp: 80 } }
    },
    {
        id: 'tower-46',
        name: '46층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 19, blackPattern: 5, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 300, exp: 80 }, repeatClear: { gold: 30, exp: 80 } }
    },
    {
        id: 'tower-47',
        name: '47층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 15, blackPattern: 4, whitePattern: 5, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 300, exp: 80 }, repeatClear: { gold: 30, exp: 80 } }
    },
    {
        id: 'tower-48',
        name: '48층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 18, blackPattern: 3, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 300, exp: 80 }, repeatClear: { gold: 30, exp: 80 } }
    },
    {
        id: 'tower-49',
        name: '49층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 2, white: 17, blackPattern: 7, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 300, exp: 80 }, repeatClear: { gold: 30, exp: 80 } }
    },
    {
        id: 'tower-50',
        name: '50층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 18, blackPattern: 6, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 50,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 80, items: [{ itemId: '장비상자3', quantity: 1 }] }, repeatClear: { gold: 30, exp: 80 } }
    },
    // 51-60층: 자동계가 턴 60턴
    {
        id: 'tower-51',
        name: '51층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 19, blackPattern: 5, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 60,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 400, exp: 80 }, repeatClear: { gold: 40, exp: 80 } }
    },
    {
        id: 'tower-52',
        name: '52층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 17, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 60,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 400, exp: 80 }, repeatClear: { gold: 40, exp: 80 } }
    },
    {
        id: 'tower-53',
        name: '53층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 19, blackPattern: 3, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 60,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 400, exp: 80 }, repeatClear: { gold: 40, exp: 80 } }
    },
    {
        id: 'tower-54',
        name: '54층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 17, blackPattern: 2, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 60,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 400, exp: 80 }, repeatClear: { gold: 40, exp: 80 } }
    },
    {
        id: 'tower-55',
        name: '55층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 17, blackPattern: 3, whitePattern: 5, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 60,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 80, items: [{ itemId: '재료상자3', quantity: 1 }] }, repeatClear: { gold: 40, exp: 80 } }
    },
    {
        id: 'tower-56',
        name: '56층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 7, white: 19, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 60,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 400, exp: 80 }, repeatClear: { gold: 40, exp: 80 } }
    },
    {
        id: 'tower-57',
        name: '57층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 8, white: 21, blackPattern: 1, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 60,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 400, exp: 80 }, repeatClear: { gold: 40, exp: 80 } }
    },
    {
        id: 'tower-58',
        name: '58층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 19, blackPattern: 4, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 60,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 400, exp: 80 }, repeatClear: { gold: 40, exp: 80 } }
    },
    {
        id: 'tower-59',
        name: '59층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 20, blackPattern: 6, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 60,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 400, exp: 80 }, repeatClear: { gold: 40, exp: 80 } }
    },
    {
        id: 'tower-60',
        name: '60층',
        level: 'tower' as any,
        actionPointCost: 4,
        boardSize: 11,
        targetScore: { black: 0, white: 0 },
        placements: { black: 2, white: 19, blackPattern: 8, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 60,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 80, items: [{ itemId: '다이아꾸러미3', quantity: 1 }] }, repeatClear: { gold: 40, exp: 80 } }
    },
    // 61-80층: 자동계가 턴 70턴, 바둑판크기 13줄
    {
        id: 'tower-61',
        name: '61층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 1, white: 20, blackPattern: 8, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 500, exp: 150 }, repeatClear: { gold: 50, exp: 150 } }
    },
    {
        id: 'tower-62',
        name: '62층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 2, white: 21, blackPattern: 7, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 500, exp: 150 }, repeatClear: { gold: 50, exp: 150 } }
    },
    {
        id: 'tower-63',
        name: '63층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 23, blackPattern: 6, whitePattern: 1, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 500, exp: 150 }, repeatClear: { gold: 50, exp: 150 } }
    },
    {
        id: 'tower-64',
        name: '64층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 22, blackPattern: 7, whitePattern: 5, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 500, exp: 150 }, repeatClear: { gold: 50, exp: 150 } }
    },
    {
        id: 'tower-65',
        name: '65층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 22, blackPattern: 5, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 150, items: [{ itemId: '골드 꾸러미4', quantity: 1 }] }, repeatClear: { gold: 50, exp: 150 } }
    },
    {
        id: 'tower-66',
        name: '66층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 6, white: 21, blackPattern: 5, whitePattern: 5, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 500, exp: 150 }, repeatClear: { gold: 50, exp: 150 } }
    },
    {
        id: 'tower-67',
        name: '67층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 19, blackPattern: 5, whitePattern: 5, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 500, exp: 150 }, repeatClear: { gold: 50, exp: 150 } }
    },
    {
        id: 'tower-68',
        name: '68층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 23, blackPattern: 6, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 500, exp: 150 }, repeatClear: { gold: 50, exp: 150 } }
    },
    {
        id: 'tower-69',
        name: '69층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 21, blackPattern: 5, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 500, exp: 150 }, repeatClear: { gold: 50, exp: 150 } }
    },
    {
        id: 'tower-70',
        name: '70층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 23, blackPattern: 5, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 150, items: [{ itemId: '장비상자4', quantity: 1 }] }, repeatClear: { gold: 50, exp: 150 } }
    },
    {
        id: 'tower-71',
        name: '71층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 22, blackPattern: 6, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 600, exp: 150 }, repeatClear: { gold: 60, exp: 150 } }
    },
    {
        id: 'tower-72',
        name: '72층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 24, blackPattern: 7, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 600, exp: 150 }, repeatClear: { gold: 60, exp: 150 } }
    },
    {
        id: 'tower-73',
        name: '73층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 20, blackPattern: 4, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 600, exp: 150 }, repeatClear: { gold: 60, exp: 150 } }
    },
    {
        id: 'tower-74',
        name: '74층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 19, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 600, exp: 150 }, repeatClear: { gold: 60, exp: 150 } }
    },
    {
        id: 'tower-75',
        name: '75층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 23, blackPattern: 5, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 150, items: [{ itemId: '재료상자4', quantity: 1 }] }, repeatClear: { gold: 60, exp: 150 } }
    },
    {
        id: 'tower-76',
        name: '76층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 22, blackPattern: 5, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 600, exp: 150 }, repeatClear: { gold: 60, exp: 150 } }
    },
    {
        id: 'tower-77',
        name: '77층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 23, blackPattern: 4, whitePattern: 1, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 600, exp: 150 }, repeatClear: { gold: 60, exp: 150 } }
    },
    {
        id: 'tower-78',
        name: '78층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 21, blackPattern: 6, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 600, exp: 150 }, repeatClear: { gold: 60, exp: 150 } }
    },
    {
        id: 'tower-79',
        name: '79층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 21, blackPattern: 7, whitePattern: 5, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 600, exp: 150 }, repeatClear: { gold: 60, exp: 150 } }
    },
    {
        id: 'tower-80',
        name: '80층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 21, blackPattern: 6, whitePattern: 6, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 70,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 150, items: [{ itemId: '다이아꾸러미4', quantity: 1 }] }, repeatClear: { gold: 60, exp: 150 } }
    },
    // 81-100층: 자동계가 턴 80턴
    {
        id: 'tower-81',
        name: '81층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 21, blackPattern: 5, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 700, exp: 150 }, repeatClear: { gold: 70, exp: 150 } }
    },
    {
        id: 'tower-82',
        name: '82층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 21, blackPattern: 5, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 700, exp: 150 }, repeatClear: { gold: 70, exp: 150 } }
    },
    {
        id: 'tower-83',
        name: '83층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 2, white: 21, blackPattern: 7, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 700, exp: 150 }, repeatClear: { gold: 70, exp: 150 } }
    },
    {
        id: 'tower-84',
        name: '84층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 23, blackPattern: 6, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 700, exp: 150 }, repeatClear: { gold: 70, exp: 150 } }
    },
    {
        id: 'tower-85',
        name: '85층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 0, white: 22, blackPattern: 8, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 150, items: [{ itemId: '재료상자5', quantity: 1 }] }, repeatClear: { gold: 70, exp: 150 } }
    },
    {
        id: 'tower-86',
        name: '86층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 2, white: 24, blackPattern: 8, whitePattern: 2, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 700, exp: 150 }, repeatClear: { gold: 70, exp: 150 } }
    },
    {
        id: 'tower-87',
        name: '87층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 24, blackPattern: 7, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 700, exp: 150 }, repeatClear: { gold: 70, exp: 150 } }
    },
    {
        id: 'tower-88',
        name: '88층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 25, blackPattern: 8, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 700, exp: 150 }, repeatClear: { gold: 70, exp: 150 } }
    },
    {
        id: 'tower-89',
        name: '89층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 25, blackPattern: 8, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 700, exp: 150 }, repeatClear: { gold: 70, exp: 150 } }
    },
    {
        id: 'tower-90',
        name: '90층',
        level: 'tower' as any,
        actionPointCost: 5,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 1, white: 25, blackPattern: 12, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 150, items: [{ itemId: '장비상자5', quantity: 1 }] }, repeatClear: { gold: 70, exp: 150 } }
    },
    {
        id: 'tower-91',
        name: '91층',
        level: 'tower' as any,
        actionPointCost: 6,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 2, white: 22, blackPattern: 8, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 800, exp: 150 }, repeatClear: { gold: 80, exp: 150 } }
    },
    {
        id: 'tower-92',
        name: '92층',
        level: 'tower' as any,
        actionPointCost: 6,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 23, blackPattern: 9, whitePattern: 5, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 800, exp: 150 }, repeatClear: { gold: 80, exp: 150 } }
    },
    {
        id: 'tower-93',
        name: '93층',
        level: 'tower' as any,
        actionPointCost: 6,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 25, blackPattern: 10, whitePattern: 4, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 800, exp: 150 }, repeatClear: { gold: 80, exp: 150 } }
    },
    {
        id: 'tower-94',
        name: '94층',
        level: 'tower' as any,
        actionPointCost: 6,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 26, blackPattern: 6, whitePattern: 1, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 800, exp: 150 }, repeatClear: { gold: 80, exp: 150 } }
    },
    {
        id: 'tower-95',
        name: '95층',
        level: 'tower' as any,
        actionPointCost: 6,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 27, blackPattern: 7, whitePattern: 0, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 150, items: [{ itemId: '재료상자6', quantity: 1 }] }, repeatClear: { gold: 80, exp: 150 } }
    },
    {
        id: 'tower-96',
        name: '96층',
        level: 'tower' as any,
        actionPointCost: 6,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 25, blackPattern: 8, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 800, exp: 150 }, repeatClear: { gold: 80, exp: 150 } }
    },
    {
        id: 'tower-97',
        name: '97층',
        level: 'tower' as any,
        actionPointCost: 6,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 5, white: 30, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 800, exp: 150 }, repeatClear: { gold: 80, exp: 150 } }
    },
    {
        id: 'tower-98',
        name: '98층',
        level: 'tower' as any,
        actionPointCost: 6,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 31, blackPattern: 7, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 800, exp: 150 }, repeatClear: { gold: 80, exp: 150 } }
    },
    {
        id: 'tower-99',
        name: '99층',
        level: 'tower' as any,
        actionPointCost: 6,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 3, white: 32, blackPattern: 8, whitePattern: 1, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 800, exp: 150 }, repeatClear: { gold: 80, exp: 150 } }
    },
    {
        id: 'tower-100',
        name: '100층',
        level: 'tower' as any,
        actionPointCost: 6,
        boardSize: 13,
        targetScore: { black: 0, white: 0 },
        placements: { black: 4, white: 40, blackPattern: 6, whitePattern: 3, centerBlackStoneChance: 0 },
        timeControl: { type: 'byoyomi', mainTime: 5, byoyomiTime: 30, byoyomiCount: 5 },
        autoScoringTurns: 80,
        missileCount: 1,
        hiddenCount: 1,
        rewards: { firstClear: { gold: 0, exp: 300, items: [{ itemId: '장비상자6', quantity: 1 }] }, repeatClear: { gold: 80, exp: 300 } }
    },
];

